# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 0
/tracking/verbose 0
/run/verbose 1
/analysis/verbose 0
#/process/had/verbose 0
#/process/em/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Execute setting
/control/execute Co60.mac

